name: Bug Report
description: Report a bug in the CAYP specification or examples
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us address it.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this bug affect?
      options:
        - Specification
        - JSON Schema
        - Examples
        - Documentation
        - Tools (validator/migrator)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Step one
        2. Step two
        3. ...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example CAYP Configuration
      description: If applicable, provide a minimal CAYP config that demonstrates the issue
      render: yaml
      placeholder: |
        cayp_version: "1.0"
        name: "example"
        # ...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Include relevant environment information:
        - CAYP Version
        - Tool/Parser (if applicable)
        - Operating System
      placeholder: |
        - CAYP Version: 1.0.0
        - Tool: cayp-validator v0.1.0
        - OS: Ubuntu 22.04

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
      placeholder: Add any other context here...

  - type: checkboxes
    id: search
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar issues
          required: true
        - label: I have read the specification
          required: true
        - label: This is a bug, not a feature request
          required: true
